### ISSUE TITLE
app.get should handle HEAD requests

### ISSUE THREAD

**Issue by alexgleason** [honojs/hono#1130]
Ideally, HEAD requests would be matched by `app.get()` routes and it would only return the headers (no body).

It's common for other libraries ([like Express](https://expressjs.com/en/4x/api.html#app.METHOD)) to do this as a convenience, so you don't have to specify an `app.head()` for every single route.

**Comment by yusukebe** [comment]
Hi @alexgleason!

Thanks for raising the issue. I'm considering whether we should implement this and, if so, how we should go about it.

If we decide to implement it so that when a HEAD request comes in, `app.get()` always handles it and responds without a body, disabling `app.head()`, it would be easy to implement. Like below:

* `HEAD /foo` will always be replaced with `GET /foo`, `app.get()` will handle it, and return the response without the body.
* Users can't define `app.head()`.

But, it's more challenging (for me) to implement with `app.head()`:

* `HEAD /foo` will be handled by `app.head('/foo')` if it's registered.
* If it was not matched, it falls back to `GET /foo`.

Perhaps the "disable `app.head()`" pattern would be acceptable if we decide that users should not define HEAD responses themselves. However, I'm not sure which approach is better at the moment.

@usualoma 

What do you think? We need to consider whether we should implement this and how we should do it.

**Comment by yusukebe** [comment]
I'm considering this issue.

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD), the HEAD method is defined as follows:

> The HTTP HEAD method requests the [headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers) that would be returned if the HEAD request's URL was instead requested with the HTTP [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) method.

So, I think it's acceptable to adopt the following pattern:

* `HEAD /foo` will always be replaced with `GET /foo`, `app.get()` will handle it, and return the response without the body.
* Users can't define `app.head()`.

In addition, according to the specification, the HEAD method should not be defined by users, so this wouldn't be a new feature, but rather a "fix". Therefore, the release including this fix would be a "patch" or "minor" release.

**Comment by alexgleason** [comment]
I agree @yusukebe !

**Comment by yusukebe** [comment]
Created the two PR:

1. Built-in pattern #1142 
2. Middleware pattern #1143 

I think "2. Middleware pattern" is better.

**Comment by renhiyama** [comment]
I think 1st one would be better. since MDN has stated a web server should respond to HEAD request as GET method without body, I think that's the web specification, right? So I think it should be enabled by default, and should be available to be disabled via `new Hono({autoResolveHEAD: false})` way.

Hono follows web standards, and so I think following MDN docs is the way to go.

Alternative thought;
If hono disables this feature by default, and the developer (usually) has no idea that HEAD reqs must be resolved automatically, it might not help in cases like where you can download files from a made-with-hono website will not inform the browser about the download size, and I have seen cases like this. Users will not inform web devs about this part, and most of the time web devs cant be contacted or any problems may arise.
I want to know whether enabling this by default creates any problem or lowers down the performance of hono.

**Comment by yusukebe** [comment]
Closed!

**Comment by mjomble** [comment]
I highly recommend documenting this behavior.

There is nothing [here](https://hono.dev/docs/api/routing#basic) that explains how HEAD requests are routed.

I assumed I have to write my own handler for them (using `app.on('HEAD', ...)`) and was confused by why that code wasn't getting executed as I tested HEAD requests. And even more confused when the requests worked anyway.

Took some digging to find out this is the expected, but undocumented behavior in Hono.

**Comment by yusukebe** [comment]
Hi @mjomble 

Thank you for the advice. If you are okay, can you create the PR for it on https://github.com/honojs/website?

**Comment by mjomble** [comment]
I don't feel familiar enough with the specific implementation details of this feature to document it.

**Comment by yusukebe** [comment]
@mjomble Okay, I'll do it later!

**Comment by riderx** [comment]
hey @yusukebe we are in 2026 and i still cannot find a the way to handle HEAD request properly in the Doc.
neither AI. It's a bit funny i would love to help,

**Comment by riderx** [comment]
ok i made a PR i hope this can help https://github.com/honojs/website/pull/859

**Comment by yusukebe** [comment]
Hi @riderx 

Thank you! I'm missing it completely. I've left the comment on the PR. Check it.
