### ISSUE TITLE
Support for returning `jsonT` with multiple structures

### ISSUE THREAD

**Issue by sor4chi** [honojs/hono#1207]
If the value returned by `jsonT` has several different structures, a type error will occur.

For example, if an early return returns a `jsonT` of exactly the same type, this is not a type error

```ts
import { Hono } from "hono";

const app = new Hono();

const route = app.get("/message", (c) => {
  const ok = Math.random() > 0.5;

  if (ok) {
    return c.jsonT({
      message: "success",
    });
  }

  return c.jsonT({
    message: "failed",
  });
});

export type AppType = typeof route;
```

However, when multiple `jsonT` types are returned by an early return, a type error occurs.

```ts
import { Hono } from "hono";

const app = new Hono();

const route = app.get("/message", (c) => {
  const ok = Math.random() > 0.5;

  if (ok) {
    return c.jsonT({
      type: "success",
      user: {
        name: "John",
        age: 20,
      },
    });
  }

  return c.jsonT({
    type: "error",
    message: "You have to login",
  });
});

export type AppType = typeof route;
```

Is this usage expected?

**Comment by sor4chi** [comment]
This would be a way to take care of the problem, but I am not sure if this implementation is a good idea.

```ts
import { Hono } from "hono";

const app = new Hono();

type Res =
  | {
      type: "success";
      user: {
        name: string;
        age: number;
      };
    }
  | {
      type: "error";
      message: string;
    };

const route = app.get("/message", (c) => {
  const ok = Math.random() > 0.5;
  let res: Res;

  if (ok) {
    res = {
      type: "success",
      user: {
        name: "John",
        age: 20,
      },
    };
  } else {
    res = {
      type: "error",
      message: "You have to login",
    };
  }

  return c.jsonT(res);
});

export type AppType = typeof route;
```

**Comment by yusukebe** [comment]
Hi @sor4chi !

Thanks for creating the issue.

> Is this usage expected?

Yes. With the current specification, different types of returns are not allowed, so we have to return the same structure regardless of "success" or "error".

```ts
// Not okay!!
if (ok) {
  return c.jsonT({
    success: true,
    message: 'Error!',
  })
}
return c.jsonT({
  error: true,
  message: 'Success!',
})
```

```ts
// Okay!! (but, it might throw errors due to another issue)
if (ok) {
  return c.jsonT({
    success: true,
    message: 'Error!',
  })
}
return c.jsonT({
  success: false,
  message: 'Success!',
})
```

There are two reasons for this.

1. If we decided to use the same structure, it's easy to notice that the "success" and "error" types are different. And in the Hono Client-side, it will be simpler to handle response, because the type is always the same structure.
2. Actually, it's difficult to implement support for multiple structures.

"2" is significant. I'm not sure of the best way to implement it, and if we could, I believe the type definition would become very complex.

**Comment by yusukebe** [comment]
Hi @sor4chi 

> I was surprised that in the second example, success is inferred as a false type and not as a bool.

Yes, I think so. But this weird behavior is fixed with this PR #1208 and the released a little while ago.

> Would it be appropriate to use is assertion or other type guards to handle the types safely on the client side?

I don't think you need to do anything special in this case. The data decoded from `req.json()` will be properly typed.

<img width="357" alt="Screenshot 2023-06-30 at 0 07 02" src="https://github.com/honojs/hono/assets/10682/3cfe415f-f842-4614-aced-a50862570c92">

Or you can use `InferResponseType`:

```ts
const client = hc<AppType>('/')
const $get = client.message.$get
type ResponseType = InferResponseType<typeof $get>
```

ResponseType will be:

```ts
type ResponseType = {
    success: string;
    message: string;
}
```

**Comment by sor4chi** [comment]
@yusukebe 
I see that the patch is out! Thank you for letting me know.

And I see there is an `InferResponseType`...! That was my first time to know, thank you!

**Comment by sor4chi** [comment]
Thank you for taking the time to answer my questions.
