### ISSUE TITLE
Use Vitest

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1390]
It's fast.

**Comment by ThatOneBro** [comment]
I converted the main test suite to `vitest`, it seems to be similar in speed. Maybe the Hono test suite is too fast already 😜 

Jest:
<img width="950" alt="Screen Shot 2023-09-03 at 8 03 28 PM" src="https://github.com/honojs/hono/assets/1592008/8375cf78-6e8a-457a-b0c3-cd857efb84ad">

Vitest:
<img width="965" alt="Screen Shot 2023-09-03 at 7 59 23 PM" src="https://github.com/honojs/hono/assets/1592008/5db8965e-7a60-4291-af65-674c588059a9">

Two seconds faster, but still, maybe it can be made faster if we run things concurrently. I tried it but I think we have to adjust it fine-grain with `describe.concurrent` and `it.concurrent` to say which things can run concurrently, since some tests depend on the order of tests before and after I think.
