### ISSUE TITLE
Validator should throw error rather than `return c.json({ success, message })`

### ISSUE THREAD

**Issue by kevbook** [honojs/hono#1441]
### What is the feature you are proposing?

Validator should throw error rather than `return c.json({ success, message })`
So we can use onError handler to format and send the right response to the client.

**Comment by yusukebe** [comment]
@kevbook 

The `onError()` is not designed for the validation error.  Write like the following:

```ts
app.post(
  '/',
  validator('json', (data, c) => {
    if (!data.title) {
      return c.json({
        success: false
      }, 400)
    }
    return {
      title: data.title,
    }
  }),
  (c) => {
    return c.json({
      success: true
    }, 201)
  }
)
```

**Comment by kevbook** [comment]
Read the code base properly. This error is not validation error. This is because of malformed json body.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yusukebe** [comment]
I see, thanks. Reopened the issue.

**Comment by ahmetbicer** [comment]
+1 for this. It would be nice to catch validator errors from onError handler.

**Comment by yusukebe** [comment]
Okay. We have to consider making it. But, it may be a breaking change. So will be included in the next major version "v4". Thanks!

**Comment by jvhellemond** [comment]
+1
I like to keep all my error responses uniform, with (translated) messages generated from onError.

**Comment by MonsterDeveloper** [comment]
@yusukebe I would suggest re-opening as the key issue is not solved: the validator just [returns the response](https://github.com/honojs/hono/blob/89f4c9691dd688d70e2b707fe87a8b97cb932136/src/validator/validator.ts#L141) from the validation function rather than `throw`-ing it:
```ts
const res = await validationFunc(value as never, c as never)
if (res instanceof Response) {
  return res
}
```

From me personally the request is to make `app.onError` a single entry-point for error handling, so all the errors returned from the API can have a standard shape, e.g.

```json
{
  "message": "You do not have permission to access this resource",
  "type": "Unauthorized",
  "types": ["Unauthorized", "Security"],
  "cause": "..."
}
```

Currently in order to modify the shape of errors returned from the validators (`sValidator`, `zValidator`, etc) every call should have a `hook` that would throw the validation error/return a modified response.

A solution might be a `shouldThrow` option passed to the validator, so the error can be handled in `app.onError`. Example:

```ts
app.post("/",
  sValidator("json", z.object({}), { shouldThrow: true }),
  async c => {
    // ...
  }
)
```

**Comment by yusukebe** [comment]
Hi @MonsterDeveloper 

I thought about that, but I think it's okay not to add the `shouldThrow` option since I don't want to introduce a breaking change. You can write the following to throw an error (right?).

```ts
import { Hono } from 'hono'
import { z } from 'zod'
import { sValidator } from '@hono/standard-validator'

const schema = z.object({
  name: z.string()
})

const app = new Hono()

app.get(
  '/',
  sValidator('query', schema, (data) => {
    if (!data.success) {
      throw new Error(JSON.stringify(data.error))
    }
  }),
  async (c) => {
    const { name } = c.req.valid('query')
    return c.json({ name })
  }
)
```

This code is not so long and is easy to understand what it does.

**Comment by ayZagen** [comment]
hi @yusukebe, wouldn’t it be better to have a global option for this purpose? For such a feature, having to pass a parameter or function to each route validator seems like poor design. And this is really necessary to have.

**Comment by yusukebe** [comment]
Hey @ayZagen !

> global option for this purpose

What kind of "global option"? How can you specify it?
