### ISSUE TITLE
c.executionCtx.waitUntil is not a function (Next.js App Router)

### ISSUE THREAD

**Issue by dihmeetree** [honojs/hono#1724]
### What version of Hono are you using?

3.10.1

### What runtime/platform is your app running on?

Cloudflare Pages

### What steps can reproduce the bug?

I'm using https://github.com/cloudflare/next-on-pages to deploy a Next.js application (App Router) to Cloudflare Pages. 

To replicate this:
1) Create a fresh Next.js app with `create-next-app` (be sure to select App Router)
2. Create a hono API at `app/api/route.ts` with the following contents:
```ts
import { Hono } from 'hono'
import { handle } from 'hono/vercel'

export const runtime = 'edge';

const app = new Hono().basePath('/api')

app.get('/', (c) => {
  console.log(c.executionCtx) // Note how this only prints { params: undefined } (Where is waitUntil)?
  return c.json({
    message: 'Hello Next.js!',
  })
})

export const GET = handle(app)
```

I can access `c.executionCtx` just fine when using pages, but with App Router I'm unable to access it for some reason. I want to be able to access `waitUntil` on `executionCtx`.

### What is the expected behavior?

I should be able to access the `c.executionCtx.waitUntil` function.

### What do you see instead?

The only thing in `c.executionCtx` is `{ params: undefined }`

**Comment by chimame** [comment]
Certainly, `waitUntil` was indeed not found. Upon inspecting the code, it appears that in Hono, the Context of the Request received by Next.js is configured.
https://github.com/honojs/hono/blob/3b71dc647fb5ed2d648f0df1276d36ce4f3a58eb/src/adapter/vercel/handler.ts#L6-L9

However, the issue lies not with Hono but with the Next.js App Router. As evident from this issue, when using the App Router, the inability to retrieve `waitUntil` is the cause.
https://github.com/vercel/next.js/issues/50522

Unfortunately, even when using Hono, `waitUntil` cannot be used with the App Router.

**Comment by yusukebe** [comment]
This seems to be closed. Thanks.
