### ISSUE TITLE
Any concern adding contributors into the honojs org?

### ISSUE THREAD

**Issue by metrue** [honojs/hono#212]

**Comment by yusukebe** [comment]
Hi @metrue !

I have thought about it but have no plans to do it *soon*. As the project grows and becomes used by more people, I will add the contributors to honojs org.

**Comment by yusukebe** [comment]
We are considering it at #350

**Comment by yusukebe** [comment]
Hi @metrue and @usualoma !

I want to invite both of you to "*honojs* org" on GitHub. Please become a member of this "org".

Basically, I will review and merge the PRs, and do releasing. Nothing different from now.
However, I would like to have help if I become ill or otherwise unable to respond to these things.

We may also change our approach to "org" in the future.

How about you? If you don't like it, please feel free to refuse 👍

**Comment by metrue** [comment]
I'm happy to help.

**Comment by usualoma** [comment]
With pleasure 👍

**Comment by yusukebe** [comment]
Hi @metrue , @usualoma 

Just to let you know, I've started the individual GitHub Sponsor program and added the button to this repository.

If you ( just @metrue and @usualoma ) want to add your sponsor button, you could edit the [.github/FUNDING.yml](https://github.com/honojs/hono/blob/main/.github/FUNDING.yml).

**Comment by usualoma** [comment]
Thanks! I will consider it.

**Comment by yusukebe** [comment]
We can close this. Thanks!
