### ISSUE TITLE
ExecutionContext type missing `abort` method

### ISSUE THREAD

**Issue by Cherry** [honojs/hono#2341]
### What version of Hono are you using?

4.1.0

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

The latest version of Hono uses a type like this:
```ts
declare interface ExecutionContext {
  waitUntil(promise: Promise<any>): void;
  passThroughOnException(): void;
}
```

But the latest version of Workers Types (`4.20240312.0`) now includes an `abort` method, so it looks like this:
```ts
declare interface ExecutionContext {
  waitUntil(promise: Promise<any>): void;
  passThroughOnException(): void;
  abort(reason?: any): void;
}
```

Reference: https://github.com/Cloudflare-Mining/Cloudflare-Datamining/blob/f3eb65cf6548395775b58955b5c0d4543b9e2d2a/data/workers-types/experimental/index.ts#L313

So if you have a function that expects a context like:

```ts
function fooBar(ctx: ExecutionContext) {
	///stuff
}
```

And then try to pass it `context.executionCtx`, you now get an error:
```Property 'abort' is missing in type 'import("e:/xxx/node_modules/hono/dist/types/context").ExecutionContext' but required in type 'ExecutionContext'.```

### What is the expected behavior?

Not to error

### What do you see instead?

```Property 'abort' is missing in type 'import("e:/xxx/node_modules/hono/dist/types/context").ExecutionContext' but required in type 'ExecutionContext'.```

**Comment by yusukebe** [comment]
Hi @Cherry 

Indeed, it reproduced.

However, I think we cannot add `abort` to Hono's `ExecutionContext` type. Since `abort` is an experimental feature, we do not want to provide `abort` to users who do not have it enabled.

I think we have another solution. If `ExecutionContext` is exported from `hono` and defined as follows on the user side, `c.executionContext.abort` can be used even in the context of Hono.

```ts
declare module 'hono' {
  interface ExecutionContext {
    waitUntil(promise: Promise<any>): void
    passThroughOnException(): void
    abort(reason?: any): void
  }
}
```

<img width="677" alt="Screenshot 2024-03-13 at 7 19 24" src="https://github.com/honojs/hono/assets/10682/9f0770b3-17e0-4183-a9d9-9d4caa7c3db7">

What do you think? If this is ok, I'll make a fix to export `ExecutionContext` from `hono`.

**Comment by Cherry** [comment]
Thanks @yusukebe, this sounds like a good solution.
