### ISSUE TITLE
feat: better error messages for status code errors

### ISSUE THREAD

**Issue by MathurAditya724** [honojs/hono#2971]
### What is the feature you are proposing?

There are quite some issues devs are having in Discord when Hono gives errors for status codes. E.g. - returning JSON data with status codes `204` and `205`. Here is the discussion - https://discord.com/channels/1011308539819597844/1250825773355372664.

The error message doesn't convey the issue too well - `TypeError: Response constructor: Invalid response status code 205`, if we have more helpful messages so that they can understand the error better with links to MDN docs, that would be nice. We also haven't mentioned this behavior in the docs, but showing a good error message in the console should be enough for now.

We can later work on other error messages, to have links and resources to debug easily debug them. (This is something we can deal with later)

I can create a PR for this

**Comment by yusukebe** [comment]
Hi @MathurAditya724 

This error is thrown when initializing `Response` with status 204 or 205:

```ts
new Response('foo', { status: 204 })
```

So, actually, Hono does not throw it. It depends on the runtimes. So, the error message and result are different between runtimes:

* Node.js: `TypeError: Response constructor: Invalid response status code 204`
* Deno: `TypeError: Response with null body status cannot have the body`
* Cloudflare Workers: ` TypeError: Response with null body status (101, 204, 205, or 304) cannot have a body.`
* Bun: No error message

Indeed, the message is not friendly, and we can handle it in Hono's core. But I think it's out of Hono's scope because it's about the API of `Response`, and honestly, I don't want to add some code for it to keep the core of Hono small, though it will not be a significant change.

@usualoma 

What do you think of this?

**Comment by MathurAditya724** [comment]
Thank you for your responses. I understand why you are saying this, but we'll need to consider a solution. Because when the error happens nobody thinks that the error is coming from the runtime, they are more like 'Hono crashed for some reason'!

Possible solutions -
1. Add a helpful error/warning message when this happens
2. Can show type errors for these
3. Add docs

If you don't want to add this to core then we should add this in the docs. We need to think about the DX and this can help devs resolve these issues faster in place of asking it on Discord and waiting for someone to respond. Maybe @NicoPlyley can add to this, but I would suggest we should at least add this in the docs if not in the core.

**Comment by NicoPlyley** [comment]
Hi @MathurAditya724,

I see the pros and cons of both sides here. I am leaning more toward this is an error that should be handled by the runtime environment. Adding an error could break someone's code in Bun who might be returning a response and not getting an error.

I looked into the history of mentioned of these response codes on GitHub and Discord, everyone seems to understand that the body cannot be sent when returning those status codes. There were only questions about how to send a null body. I think it's reasonable for devs to understand the status code they are sending and the standards behind it. I would expect other frameworks to also have the same approach but I would be interested to see if that's the case.

Ultimately, I think being handled by the runtimes is sufficient.

**Comment by MathurAditya724** [comment]
Okay, I think this discussion is more than enough for now if someone has this issue in the future. Thank you everyone for sharing your thoughts.

But I do think we should add more things in Hono, maybe not in the core but like a wrapper/middleware to improve the DX and build APIs faster. Maybe not today but in the future.
