### ISSUE TITLE
OAuth2 client reccomendations

### ISSUE THREAD

**Issue by byt3bl33d3r** [honojs/hono#332]
This is more of a question than an issue, i'm trying to use Hono + Cloudflare workers to implement a OAuth2 Authorization Code Flow for the backend of a Web UI.

Is there an OAuth2 client you'd recommend for Hono?

 the only one I've found that seems to work is https://github.com/panva/oauth4webapi, but it seems like I would have to wrap it in a Middleware to make it work "nicely" with Hono. Just wanted to check and see if anyone knew of a better one before i went down the rabbit hole of making it work nicely.

Thanks!

**Comment by yusukebe** [comment]
Hi @byt3bl33d3r! thank you for using Hono!

It's a good idea to use Hono for an OAuth2 client, but I've not built an application about OAuth.

`panva/oauth4webapi` does not seem to be bad to implement OAuth2 client. It does not depend on other libraries. And, I think it's good to wrap it in a Middleware. Because there is "*Custom Middleware* for such purpose. That's about all I can say.

And then, feel free to create an issue!

**Comment by byt3bl33d3r** [comment]
I managed to get that library working with Hono. Thanks

**Comment by panva** [comment]
@byt3bl33d3r care to share your implementation? Either publicly as an example or privately such that I may create an example out of it.

Thank you.
