### ISSUE TITLE
Types for req.parsedBody

### ISSUE THREAD

**Issue by gkiely** [honojs/hono#341]
Is it possible to add the ability to pass a generic type to bodyParse?
https://github.com/honojs/hono/blob/master/src/middleware/body-parse/index.ts#L7

Example:
```ts
app.post('/api/post/:id', bodyParse(), async c => {
  const body = c.req.parsedBody;
});
```

<img width="613" alt="image" src="https://user-images.githubusercontent.com/1948935/177051271-2c5212a1-c814-4f86-85e3-12942437426b.png">

**Comment by yusukebe** [comment]
That may be difficult, but it's a good theme. I'll give it some more thought.

**Comment by gkiely** [comment]
I closed it as I ended up using zod to validate it, as technically the payload is unknown at runtime.
<img width="466" alt="image" src="https://user-images.githubusercontent.com/1948935/177061910-4dd48479-3bb2-470f-a6fa-e0e8315ece20.png">


Perhaps moving it to type `unknown` would be good? It would prevent a user from having a runtime error.

**Comment by yusukebe** [comment]
It is certainly one way to use *zod*. However, I think it's difficult to make it `unknown` because there are use cases to use `parsedBody` directly not using a validator such as *zod*.

For example, I think it's good to make it a function, like `c.req.parsed body()`. In this case, we can pass the generics easily.

```ts
const props = c.req.parsedBody<Props>()
```

Though, it's still in the planning stages.
