### ISSUE TITLE
Record key returned by `c.req.header()` is always lowercase

### ISSUE THREAD

**Issue by sushichan044** [honojs/hono#3416]
### What version of Hono are you using?

4.6.1

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

1. Clone this repo https://github.com/sushi-chaaaan/header-normalize
2. Start dev server with `pnpm dev`
3. Request `GET /hono/upper` | `GET /zod/upper` | `GET /valibot/upper` with `X-API-Key: {any string}` and it will throw 400 HTTP Exception
4. or you can check behavior with`pnpm test`

### What is the expected behavior?

The record key of the header passed to the validator respects the case of the actual HTTP Header.

### What do you see instead?

All header names passed to the validator are in lowercase, so checking with uppercase header names will always fail
### Additional information

The direct cause of this behavior is that the header name retrieved in `Headers.forEach()` is always in lowercase.

https://github.com/honojs/hono/blob/0edb243a7481a395f017625ba7493e1b6271decb/src/request.ts#L175-L186

https://developer.mozilla.org/en-US/docs/Web/API/Headers/forEach

**Comment by sushi-chaaaan** [comment]
HTTP headers are not case sensitive in the specification, so it may not be a simple solution.

**Comment by sushi-chaaaan** [comment]
It has no relation to validation, though,
It may be worth adding to the documentation that the case treatment changes
between `c.req.header(NAME)` and `c.req.header()`.

**Comment by yusukebe** [comment]
Hi @sushi-chaaaan 

Thank you for this issue. This problem is challenging to find out. 

The hard thing about this issue is that it is not really a bug. `c.req.header()` returning lowercases is not a bug; it's from the spec of the HTTP header, which can not be specified if it's lower or upper. And I think it's very difficult to handle this problem in `src/validator/validator.ts` or something of the Validator layer.

So, as you said, It's okay to add a description to our docs. https://github.com/honojs/website/pull/494 is nice.

One more, I think it's better to add a warning or caution to https://hono.dev/docs/guides/validation for the keys of the header that the user wants to validate should be lowercase. If you agree, can you create a PR, too?

**Comment by sushi-chaaaan** [comment]
Thanks @yusukebe 

Ithink that additional documentation should be written about validation, so I will create a PR.

I'm also considering aboutTypeScript type approach, but I'm not sure if it will work.

**Comment by sushi-chaaaan** [comment]
Perhaps zValidator, vValidator, etc. could use such an API to generate an error for uppercase keys.
However, the error may not be human-readable.

https://zod.dev/?id=keyof
https://valibot.dev/api/keyof/

**Comment by sushi-chaaaan** [comment]
I create a PR to Docs to add a warning on validating headers.

I also tried to display an TS error if uppercase key contained in Zod Schema with TypeScript,
but it seems to be a non-Human-readable error.

https://github.com/sushi-chaaaan/header-normalize/blob/3de0607f559f61e0460b85d11df022d82a6ec7bc/src/forceLower.ts

**Comment by sushi-chaaaan** [comment]
I think it is possible to issue a warning at runtime if there is an Uppercase key in zValidator, vValidator, etc.

**Comment by yusukebe** [comment]
@sushichan044 

Thank you for working on it. I also think it's challenging, and it may be unnecessary to warn it from the framework side. So, the best way is writing documents, and you've done that!

**Comment by sushichan044** [comment]
@yusukebe 

Thanks!
I think it difficult to make any more good corrections. I'm closing this issue !
