### ISSUE TITLE
Bunjs support

### ISSUE THREAD

**Issue by ansarizafar** [honojs/hono#344]
Is there any plan for Bunjs support https://bun.sh/

**Comment by yusukebe** [comment]
Yes, or most are already done! Because Bun has Web standard API such as `Request` and `Response` like a Cloudflare or Deno. I've tried to run the minimal app using Hono on Bun. It works well! You can run the same script:

https://gist.github.com/yusukebe/0822c1629fc05027dcc8302ddaafc932

Maybe some middleware such as *jsx* are not working now (Currently, *JSX Pragma* is not supported on Bun). But, almost are working.

You will be able to start using Hono right away if you want. And the day of support for Bun completely is coming soon.

**Comment by cursecodes** [comment]
While attempting to use your demo, I found that if you try to return/res json that it breaks. Very important in my opinion, so it should be looked into. Here is my code: https://gist.github.com/cursecodes/ace9e61658b95aa4dc2d99e4fd6bffbd

**Comment by cursecodes** [comment]
Haha yes I was missing that. Unfortunately, this did not fix it.

**Comment by yusukebe** [comment]
Hi @cursecodes 

This code works well in my environment. I can't reproduce your error.

```ts
import { Hono } from 'hono'

const app = new Hono()

app.get('/', (c) => {
  return c.json({ message: 'Hello Bun!' })
})

export default {
  port: 3000,
  fetch: (req) => app.fetch(req),
}

// Run the script on bun
// bun run ./hello.ts
```

**Comment by zhusupq** [comment]
$ bun run --hot src/index.ts
error: Cannot find module "hono/dist/hono-base.js" from "C:\Users\PC\Downloads\my-dev\bun-hono-test\my-bun\node_modules\hono\dist\hono.js"

but hono-base.js is available in node-modules

**Comment by andresito87** [comment]
Hi, I got the same problem and I could fix it, following those steps:
- Delete file bun.lockb in root folder
- Delete node_modules folder if it present
- Execute the next comand in the root folder of project to clean the cache bun pm cache rm
- Finally install everything with bun install and run the project with bun run dev.
I think it is a problem with lasted and newer dependencies of the project and its cache.
