### ISSUE TITLE
RPC tries to import server-side database code into the client and make svelte crash

### ISSUE THREAD

**Issue by Extarys** [honojs/hono#3450]
### What version of Hono are you using?

4.6.3

### What runtime/platform is your app running on?

Bun 1.1.29

### What steps can reproduce the bug?

- Use EdgeDB
- Use Hono RPC and export routes types

### What is the expected behavior?

Types should be working as expected.
No server-side code should be imported in the client.

### What do you see instead?

The server console Svelte side shows:
```
Unable to interop `export * from "edgedb/dist/reflection/index.js"` in /.../Monorepo/dbschema/edgeql-js/reflection.mts, this may lose module exports. Please export "edgedb/dist/reflection/index.js" as ESM or use named exports instead, e.g. `export { A, B } from "edgedb/dist/reflection/index.js"`
```

The browser console prints:
```
TypeError: $.StrictMap is not a constructor
```

### Additional information

An employee over at EdgeDB took a look, in their words: `my suspicion is around whatever the runtime or bundler is doing (Bun? Vite?) is causing server code to be executed (bundled?) into the browser.`

Reproduction repo: https://codeberg.org/Dreamboat9222/Monorepo-Edgedb-Hono-Svelte

(All of it, we tested some stuff)
I did a lot of removing and moving locally before creating the repo, but inside the repo here's what we tried:

- "First" try: https://codeberg.org/Dreamboat9222/Monorepo-Edgedb-Hono-Svelte/src/commit/830e6c4e0bac5db16e07b27706ad50d3314e2da4
- Second try: https://codeberg.org/Dreamboat9222/Monorepo-Edgedb-Hono-Svelte/src/commit/5c8b4d9e4b903c96312ff684030e009f739f1bce
- Third try (hono version bumped too): https://codeberg.org/Dreamboat9222/Monorepo-Edgedb-Hono-Svelte/src/commit/692dd416eda436fcaf194568942faf07d102dc46

First attempt is mostly the last thing I tried locally that threw the error.

My second attempt was to simply even further the repo and make a single route inside index and remove the middleware.
As soon as `e` is called inside the route (even if the result isn't returned), the error occurs.

Third attempt was to move everything edgedb related to another file with the route, the same error occurred.

Those were suggestions by Scott over at EdgeDB. Thanks to them <3

**Comment by yusukebe** [comment]
Hi @Extarys 

This is not a Hono-side bug. Your setting is wrong.

I don't know if this is the best solution, but don't export the type `AppRouter` from `backend/api-hono/src/index.ts`. If you export it from `backend/api-hono/src/route.ts`:

```ts
const app = new Hono().post('/', async (c) => {
// ...
})

export type AppType = typeof app
```

And import it in `apps/ui/src/lib/hono.ts`, the error does not appear:

```ts
import type { AppType } from '@repo/api-hono/src/route'
import { hc } from 'hono/client'
import { API_ENDPOINT } from "./config";

export const hono = hc<AppType>(API_ENDPOINT, {
//...
});
```

**Comment by askorupskyy** [comment]
The OP is actually correct here. I was encountering the same issue. 

Building my Nextjs UI with Hono RPC was building the **entire** backend, including `argon2`, which Webpack refused to build. There's a couple ways to go around it:

1. Temporary: use `openapi-hono` to create a `route`. Create an empty `OpenAPIHono`, where each handler is an empty function. Export that as an `AppType` to create a client for your app. In this case, your implementation will not be compiled. Here's a repo where I show an example: https://github.com/askorupskyy/hono-rpc-types
2. Core: change Hono to a `contract` model. `ts-rest` follows the same model and I have not encountered such issues with it. Essentially they allow you to declare the entire type of the app and then put your implementation on top of that declaration. 

This way you have `client<-contract->server` model, instead of `client<-->server`. You cannot build the client separately from the server unless you use some sort of hacks.

**Comment by askorupskyy** [comment]
@yusukebe to further expand the point...

Here's the dist from my `api/client` library.

```javascript
// dist/libs/thriveapp/api/client/main.js

...
    .openapi(
      n.users.del,
      async (e) => (
        await o.user.delete({ where: { id: e.req.param('id') } }).catch((t) => {
          E(t, 'Unable to delete user.');
        }),
        e.json(204)
      )
    )
    .openapi(n.users.update, async (e) => {
      let { profilePicture: t, ...r } = e.req.valid('form');
      await rt(e.req.param('id'), e.var.user);
      let a = t ? await vo(t, e.var.user.id) : void 0,
        s = await o.user.update({
          where: { id: e.req.param('id') },
          data: { ...r, profilePicture: a },
        });
      return e.json(s, 201);
    })
...
```

Here's the `api/client` src itself:

```typescript
import { hcWithType } from '@/thriveapp-api-routers';

export const client = hcWithType(process.env.THRIVEAPP_API_URL, {})
```

And here's my actual app:

```typescript
const mainRouter = new OpenAPIHono()
  .basePath('/api/v1')
  .route('/auth', authRouter)
  .route('/analytics', analyticsRouter)
  // and so on...

type AppType = typeof mainRouter;

const client = hc<AppType>('');
export type Client = typeof client;

export const hcWithType = (...args: Parameters<typeof hc>): Client =>
  hc<AppType>(...args);
```

I tried multiple ways to overcome this but seems like none of them really solve the problem for me without too much pain.

UPD:
Eventually I found a way around all of this by using `esbuild's declaration: true` to generate the `d.ts` for me. It works fine but I still need to build this lib every time before making any change in my web app. This could be avoided it the endpoint declarations were separated as proposed above.

**Comment by askorupskyy** [comment]
@Extarys let me know in the project's issues if you have any questions, i will be glad to help!

**Comment by yusukebe** [comment]
@askorupskyy 

Thanks.

> This way you have `client<-contract->server` model, instead of `client<-->server`. You cannot build the client separately from the server unless you use some sort of hacks.

Understood well!

But as mentioned above, it's not a Hono core bug (this may not be stuff discussed here). I'll close this issue after confirming @Extarys can work the code.

**Comment by yusukebe** [comment]
Sorry. I want to say it clarify.

> I could argue that the Hono documentation display/advertise RPC, but the RPC implementation throws server-side code into the client.

This is a doubt. With the correct setting, we can use the RPC without server-side implementation for both `client<-contract->server` and `client<-->server` models. Just use types generated from server-side.

**Comment by askorupskyy** [comment]
@Extarys 
> I'm switching from Elysia, and not to make the "one is better than the other" comparison, but I didn't encounter this issue with the other framework. Maybe I got lucky (or unlucky) 🤷‍♂️

Elysia works exactly the same as Hono in terms of type inference. In fact, most of these new TypeScript frameworks work pretty much the same, even tRPC (had that issue there as well). The only one I've seen who got it right was `ts-rest`, to which we switched at my company because `trpc` was compiling the entire backend when building our Next app and 16gb of RAM was not enough to build it.

With this compiled `d.ts` spec (linked in the Hono docs under RPC as "known issues") these frameworks don't provide much new functionality tbh. You might as well just write Golang/Java backends with Swagger docs and generate a React Query client using a third-party lib (you can also codegen `.java`, `.py`, or `.go` clients). I have another repo that explains how to implement it: https://github.com/askorupskyy/golang-nx-template

This is why the `contract` model is so cool because the contract represents your API spec without any business logic. You can just compile the contract in order to build the client. Then you can also use the contract to write actual API controllers (kind of like `@hono/zod-openapi` does except it does not let you create the client with your `routes`, only implement controllers).

**Comment by askorupskyy** [comment]
@Extarys hey sorry for the late response. So `libs/api/current` represents the default Hono behavior (which would compile and throw in the server code into the client). If you try to use that client with the web app and build, it will fail due to environment type mismatch between the two. If you use `libs/api/proposal` actually contains what you'd need to get rid of those issues you have rn.

`def` project contains the API definitions. Essentially the type of each endpoint.

```typescript
const api = new OpenAPIHono();

export const mainDefinition = api.openapi(
  helloDefinition,
  function () {} as any
);

// below you can create a client that will be exported normally.
```

This code below creates the empty Hono app with empty endpoint handlers, which when combined together will you give you a clean type without any server code.

The `proposal/routers` project container the endpoints based on these definitions.

Hopefully that makes sense, let me know.

**Comment by askorupskyy** [comment]
@Extarys the other thing you could do is compile the your hono app with `tsc` or `esbuild` and grab the `AppType` for your client from the artifact to use with your client. This way you'll have to compile the hono app each time after making a change in order for these changes to show up in your client.

**Comment by yusukebe** [comment]
@Extarys 

If you want to talk about Elysia, please do that other places. Closing this issue.

**Comment by isnifer** [comment]
Just for someone who didn't mention a difference in the typescript syntax:

❌ Wrong:
```ts
import { type AppType } from '@repo/api-hono/src/route' // imports whole module
```

✅ Correct:
```ts
import type { AppType } from '@repo/api-hono/src/route' // imports nothing to runtime code
```
