### ISSUE TITLE
How to modify the definition of executionCtx in Context interface?

### ISSUE THREAD

**Issue by bytemain** [honojs/hono#385]
<img width="844" alt="CleanShot 2022-07-16 at 00 01 27@2x" src="https://user-images.githubusercontent.com/13938334/179262070-c0b51d52-9a3e-4224-aa2a-9ac90b87e966.png">

I'm using the js module syntax, but the tsc tell me that executionCtx maybe undefined. so how can I resolve this problem?

I know I can use `c.executionCtx!.waitUntil`, is there has another solutions ?

**Comment by Code-Hex** [comment]
Is it about this?

https://github.com/honojs/hono/blob/94d94198bcceb300d8b2588cd63a99eadda14807/src/context.ts#L15


I don't have just idea but probably I think it will be resolved to use `type` instead of `interface`.

like `type Context = EventContext | ModuleContext`.

EventContext has `event` property. ModuleContext has a `executionCtx`.

**Comment by usualoma** [comment]
Oh, this looks difficult, indeed.

### Define as getter method

How about defining it as a getter method and checking it like a type guard?
https://github.com/honojs/hono/compare/master...usualoma:hono:feat-runtime-check-context

Since c.event and c.executionCtx are usually used when the user "knows exactly what he wants to do", "I wrote it, but I can't refer to it at runtime" will not happen, so the DX will hardly be compromised.


### To distinguish between different types

This is an incomplete implementation, but if we were to add a type variable to Hono, this would be the direction to go.
https://github.com/honojs/hono/compare/master...usualoma:hono:with-context-types

The type definitions are going to be quite complex and difficult to maintain.
However, for users, there may not be much confusion if ModuleContext is the primary way to write them.

**Comment by yusukebe** [comment]
Hi @Code-Hex,  @usualoma
Thank you both! You guys are idea men!

It's going to be hard to use two types such `EventContext | ModuleContext` 😕 

"Define as getter method" pattern that @usualoma said seems to be good 👍 
Let's go with "Define as getter method" pattern.

@usualoma  Could you create the PR?
