### ISSUE TITLE
serve-static middleware for node js

### ISSUE THREAD

**Issue by that-ambuj** [honojs/hono#557]
There was a lack of serve-static middleware for node.js to serve static files, As mentioned in one of the issues on honojs/node-server, we needed a serve-static middleware. I have been able to create a middleware for just that. I just need approval to submit a pull request from my repo https://github.com/that-ambuj/hono/tree/node-serve into this repo.

**Comment by yusukebe** [comment]
Hi @that-ambuj !

Sorry, we can't accept your PR because we have to make Serve Static middleware for Node.js on "honojs/node-server" repository. We don't have to put Node.js things in this repository. If you want to use Hono's utility functions in "honojs/node-server" repository, you can import them like this:

```ts
import { getFilePath } from 'hono/utils/filepath'
import { getMimeType } from 'hono/utils/mime'
```

If you want to make a PR, we are waiting for you in the honojs/node-server repository!

**Comment by that-ambuj** [comment]
I'm sorry if I come out as naive but how exactly should I import utils from hono? as a git submodule or a node module??

**Comment by yusukebe** [comment]
@that-ambuj 

You may use the npm module. I think "honojs/node-server" can depend on "hono".

**Comment by that-ambuj** [comment]
I have linked the github repo on hono as dev dependency. and I have directly imported utils from 'hono/src/utils'. Please check the pull request on honojs/node-server.
