### ISSUE TITLE
Write about `Deno supports Cache API` on honojs.dev

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#566]
Deno supports Cache API since v1.26.0:

https://github.com/denoland/deno/releases/tag/v1.26.0

**Comment by ThatOneBro** [comment]
Great! I'll write about this tomorrow. I will spend some time tomorrow filling out a lot of the middleware too. 
I want to help clear out some of the Hono backlog, and maybe start the English blog over the weekend 😄

**Comment by ThatOneBro** [comment]
@yusukebe I believe I may have found something that needs addressing before we list Deno support for the Cache middleware...
```ts
const response = c.res.clone()
if (options.wait) {
  await cache.put(key, response)
} else {
  c.executionCtx.waitUntil(cache.put(key, response)) // This line will be hit on Deno, and currently isn't supported
}
```
Because this middleware in dependent on the `FetchEvent.waitUntil()` API, it won't work on Deno. We get the `Trace: This context has no ExecutionContext` error currently. What is the best way to add support for this?

**Comment by yusukebe** [comment]
How about using `wait` option:

```ts
app.use('/wait/*', cache({ cacheName: 'my-app-v1', wait: true }))
```

**Comment by ThatOneBro** [comment]
> How about using `wait` option:

Oh wow, you're right. A simple solution. I'll add this to the docs for the Deno instructions. There is a small change to be made for to `src/middleware.ts` to export the cache middleware for Deno, otherwise it is working now 👍 

I'll finish updating the Cache page (including options) before I submit a PR for the Cache description change.

**Comment by ThatOneBro** [comment]
Hi @yusukebe, did these PRs meet the criteria for this issue? Are we ready to close this now? 👀

**Comment by yusukebe** [comment]
Yes! I'll close now!
