### ISSUE TITLE
Feature request: exception support

### ISSUE THREAD

**Issue by raiyansarker** [honojs/hono#605]
Hi,
I really liked this framework a lot, it has everything that I expect from a framework. I use NestJS heavily, while I was using honojs, I missed the exceptions support. Exceptions make the code more readable and easy to work with.
So I implemented exception handler inside honojs to make the developer experience more better. It is heavily inspired by NestJS. Here is a working **[demo](https://github.com/raiyansarker/honojs-exception-support-preview)**.

PR for the feature: #604 

Syntax looks something like this:
![exception-handler-demo](https://user-images.githubusercontent.com/38852396/196043244-85195b9e-afd5-418d-91a6-193f6bfde2df.png)

**Comment by yusukebe** [comment]
Hi @raiyansarker !

First, thank you for creating this issue and the PR.

We did not dare create an exception class. This is because `c.text()` and `c.json()` are enough for most things.

```ts
app.post('/foo', (c) => {
  return c.json({ message: 'Bad Request' }, 400)
})
```

Also, for example, the error message from Basic Authentication middleware can be changed as follows

```ts
app.use('/auth/*', async (c, next) => {
  await next()
  if (c.res.status === 401) {
    return c.json(
      {
        message: 'Unauthorized.',
      },
      401
    )
  }
})
```

By doing this, we are trying to make the code of Hono small and reduce the things developers have to consider. But, with the current implementation, it is difficult to change the output format, such as JSON or text, based on the conditions. With your proposal, this is easy.

```ts
app.onError((err, c) => {
  if (err instanceof Exception) {
    c.status(err.status)
    if (c.req.header('accept').includes('application/json')) {
      return c.json({ message: err.message })
    }
    return c.text(err.message)
  }
  return c.text('Custom Error Message', 500)
})
```

I think it's a good point. And there are a few things to fix, but the implementation is mostly fine.

If we decide to accept it, we can use this exception class to implement the error handling in the core of Hono and middleware. It's good to migrate after this PR is merged.

What do others think? If you have an opinion, let me know. esp: @metrue @usualoma

**Comment by usualoma** [comment]
I don't think there are any major issues with the current hono but it would be a good change to be able to write errors like this PR!

**Comment by yusukebe** [comment]
Hi @raiyansarker !

I have reconsidered this issue. The conclusion is that "this feature is not necessary". Because, as written above, `c.json()` and `c.text()` are enough to throw and handle errors.

```ts
app.use('/auth/*', async (c, next) => {
  await next()
  if (c.res.status === 401) {
    return c.json(
      {
        message: 'Unauthorized.',
      },
      401
    )
  }
})
```

Already, the Hono core and middleware use `c.json()` and `c.text()` to throw errors, and it is working correctly. If we want to use error objects, we can create them ourselves; I don't think we need them in Hono itself.

**Comment by yusukebe** [comment]
I think we can close this issue. If you want, feel free to reopen it.
