### ISSUE TITLE
The results of `context.param` are URL-encoded

### ISSUE THREAD

**Issue by roj1512** [honojs/hono#659]
## Current behavior

URL: http://localhost:8000/%C3%A7awa%20y%C3%AE%3F

Code:

```ts
app.get("/:text", () => {
  console.log(context.param("text"));
})
```

Output:

```ts
%C3%A7awa%20y%C3%AE%3F
```

## Expected behavior

URL: http://localhost:8000/%C3%A7awa%20y%C3%AE%3F

Code:

```ts
app.get("/:text", () => {
  console.log(context.param("text"));
})
```

Output:

```ts
çawa yî?
```

#### Version: 2.4.0

**Comment by yujong-lee** [comment]
@yusukebe 

Due to [RFC 2718](https://www.rfc-editor.org/rfc/rfc2718), URL may also include multilingual characters using utf-8 encoding.

For a certain period of time, browser didn't decode it and show encoded string in url field. But nowadays, they properly decode it. (mostly, I think)

So I think it makes sense to decode it by default when we call param().

What do you think?

**Comment by roj1512** [comment]
Yes, you should decode it. That's what I want.

**Comment by roj1512** [comment]
You're currently not decoding it.

**Comment by yusukebe** [comment]
@yujong-lee 

> But nowadays, they properly decode it. (mostly, I think)

Yes, I think so. And I've also tried it with other Node.js frameworks: Express.js and Fastify; the characters are decoded. So, let's make it decode the values when calling `param()`.

**Comment by roj1512** [comment]
I am not familiar with the codebase so I leave that to you.
