### ISSUE TITLE
Can't get hash parameter from callback url

### ISSUE THREAD

**Issue by jakesteele** [honojs/hono#711]
Hey,

I am trying to get the access_token hash parameter from my Auth0 workflow in Hono but the URL is saying its empty.

http://localhost:8787/callback#access_token=tokenvalue&expires_in=7200&token_type=Bearer&state=PENDING

Is the callback url I am hitting the endpoint with (with a real token).

```
app.get('/callback', async(c, next) => {
	const url = new URL(c.req.url);
	console.debug(url);
	return c.json(JSON.stringify(url));
});
```
I use the following code but just get:

```
GET /login 302 Found (2.51ms)
URL {
  href: 'http://localhost:8787/callback',
  origin: 'http://localhost:8787',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'localhost:8787',
  hostname: 'localhost',
  port: '8787',
  pathname: '/callback',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

The hash parameters are empty. How do I properly receive the hash values so I can start authenticating my members.

Thanks :D

**Comment by yusukebe** [comment]
Hi @jakesteele !

This behavior is not only caused by using Hono. Every Cloudflare Worker application can't get a hash parameter. The Hash parameter (fragment) is only for the client side.

* [How to access URL fragment (stuff after #) in Worker - Developers / Workers - Cloudflare Community](https://community.cloudflare.com/t/how-to-access-url-fragment-stuff-after-in-worker/197366/2)

**Comment by yusukebe** [comment]
This can be closed.
