### ISSUE TITLE
[Validator] can't parse query params correctly

### ISSUE THREAD

**Issue by unworthyEnzyme** [honojs/hono#723]
my validator schema is as follows 
```js
validator((v) => ({
    skip: v.query("skip").asNumber().isOptional(),
    take: v
      .query("take")
      .asNumber()
      .isRequired()
      .message("take argument is required"),
  })),
```
If i send a request like this `http://localhost:3000/api?take=100/` i receive an error as `Invalid Value [100]: the query parameter "take" is invalid - should be "number"`

**Comment by yusukebe** [comment]
Hi @unworthyEnzyme !

In that case, we should use `isNumeric` instead of `asNumber`.

```ts
validator((v) => ({
  take: v.query('take').isNumeric().isRequired(),
}))
```

`asNumber` means it will treat the value as `number` type , this is used for JSON body. In this case, the value of `query('take')` is always a string, so use `isNumeric`. I want to enable it to cast it using `asNumber` in the future.
