### ISSUE TITLE
add helmet security for hono

### ISSUE THREAD

**Issue by hanumanjiblog** [honojs/hono#798]
please add helmet security to secure our api

https://www.npmjs.com/package/helmet

**Comment by renhiyama** [comment]
You cant use helmet with hono. Atleast not out of the box. Helmet provides expressjs like middleware, (ie. `(req, res, next)`) rather than a low level configuration where you can fill in `c.req` and other objects. Therefore, we got two options to choose from:
- find another package that provides low level access and not just like an expressjs compatible API.
- try to polyfill support for expressjs api, I wouldn't recommend since it provides extra overhead during every request.

**Comment by jackdbd** [comment]
I wrote a generic library that can help you generating a `Content-Security-Policy` header (only that particular header, not all other headers supported by Helmet).

https://github.com/jackdbd/content-security-policy

I'm using this library in an Eleventy plugin of mine. Using the library in a Hono middleware shouldn't be different.

The only problem I see is that its dependendencies might not work in the JS runtime where the Hono app is deployed. For example, my library currently depends on [Joi](https://github.com/hapijs/joi), which in turn depends on [@hapi/hoek](https://github.com/hapijs/hoek), which uses `Buffer`. But `Buffer` is not available on Cloudflare Pages Functions (and also Cloudflare Workers I think).
