### ISSUE TITLE
[Question] Should I use v2 or wait for v3?

### ISSUE THREAD

**Issue by silvioprog** [honojs/hono#842]
Hi.

I'm going to develop a small open source CRUD application, so considering Hono as framework, but I have two questions:

- Should I wait for the V3?
- If so, when will it be released?

TIA for any information!

**Comment by yusukebe** [comment]
Hi @silvioprog ! Thanks for asking.

You don't have to wait for v3! It might be better to start developing your application with v2 right now!

Because v3's API will not be so different, it will be easy to migrate. The biggest thing about this version update is that it will allow for more things to be possible, but the basic features will remain the same.

> If so, when will it be released?

Maybe within a month 🙂

**Comment by silvioprog** [comment]
Wow, thanks a lot for the information, @yusukebe!

I had a great success testing JWT and Zod validation with Hono, I'm going to use this amazing project!
