### ISSUE TITLE
Using zod's `z.transform` makes hc client `unknown` type

### ISSUE THREAD

**Issue by kissge** [honojs/hono#946]
// Please allow me to make several posts one after another..

[https://www.typescriptlang.org/play?#code/JYWwDg9gTgL....](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLwGoEMA2wAm6bRwC+cAZlBCHAOQACAFhAHYQD0yEOAtAG5a75o1ANwAoUJFiI4ACWYRiZClWqMWI8eGjwkyReUo0OODRO3T6AY33KaatpewBTJjA2iEouN7iXmAZ3h0MDA4AF44JicAd1l5AAoASgA6AHMnGHivHxzqVlIICGoAGmyc7zR+PAIoLPL6mgBHAFcnKABPErKGiuSIACMAKydLTM8entwALhRkwKhgJlSk5KgndIAPeNYAPQBtAAYuAE4AXQBqABJWRO6JhuSYKHQmfwKoEHiAOWaQfrbEqV7t4iIC7j4wT14pZEuEAHzg+qWZKDfzMAAq8XGwJy018qycjWSfGwOHi1BabU6KVwQJxPlYrHp9x2AH5EeVQXTvIkxN0-K94I5gC54BErAAeGDtMBOCCkODBMBw8msai87qMnJs0REDz8gJBELhSIxOIsFbpTIcvIFIrc8qVUmCWoc3KUjpdHHIPpDEZjN0NPE++aLZYpNabbb7I5nK43QP1LWPZ6vd6fH5-AEOnpcjmQhrQ2FhBE45GojFYxPlPHItZEkm4cke6nJWnVnJa5k9HU4vM5DUGwW+ZyuE2S6Wy+WKkIqvLqsSdpk+HV60RAA)

![image](https://user-images.githubusercontent.com/4177010/222620374-e5e22363-b79d-4470-b149-ea29003d5c13.png)

**Comment by yusukebe** [comment]
HI @kissge !

Thanks for creating several issues; very helpful for us.

About this issue it's expected because "query parameters are always `string`", so it does not allow being `number` regardless of before or after validators. It's expected.

**BUT**

It is not good. Types before and after validators should be treated differently. So we are trying to make the following behavior in the next minor version. 

The type of validated value is "number":

<img width="325" alt="SS" src="https://user-images.githubusercontent.com/10682/222689098-9842c911-e8c2-4e9e-97b7-feba692df86d.png">

The type before validation is "string":

<img width="331" alt="SS" src="https://user-images.githubusercontent.com/10682/222689114-3e5afcf1-a873-4382-aea1-8ee81ea65f10.png">

It's a just plan, but thanks to your hints.

**Comment by yusukebe** [comment]
Since v3.1.0, Hono supports "transformation". So, this issue has been resolved.
